#!/usr/bin/env python3
"""Sync the Open Graph / Twitter Card tags across the site's static pages.

Why a script instead of hand-editing three files: crawlers do not run JS, so
every page has to carry ABSOLUTE og:/twitter: URLs in its served HTML (the
client-side setTitle() in index.html/teams.html only helps browsers). That
means the origin is repeated many times over. Keeping it here as ONE constant
makes a later domain switch a single edit:

    1. change SITE_ORIGIN below
    2. run:  python scripts/og_tags.py

Everything between the "og:begin"/"og:end" markers in each HTML file is
generated by this script -- edit it HERE, not in the HTML. The plain <title>
and <meta name="description"> tags are deliberately NOT managed: they stay
hand-written in each file, right above the generated block.

Run with --check to verify the files are in sync without writing (exit 1 if
they are not).
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# The single constant. Live GitHub Pages origin, no trailing slash.
# A custom domain later (e.g. https://hoopsmatic.com/nba-career-map) is one
# edit here + a re-run of this script.
# ---------------------------------------------------------------------------
SITE_ORIGIN = "https://jsierrahoopshype.github.io/nba-career-map"

SITE_NAME = "NBA Career Map"

# Shared share card: the career-paths map (red arcs over the US, team logos).
# 1200x630 is the size Facebook/X/LinkedIn/Slack all render without re-cropping.
OG_IMAGE_PATH = "/assets/og-career-map.png"
OG_IMAGE_WIDTH = "1200"
OG_IMAGE_HEIGHT = "630"
OG_IMAGE_ALT = ("NBA career paths drawn as red arcs across a map of the United "
                "States, with NBA team logos at each stop")

# Per-page static tags. These must read sensibly for the SECTION IN GENERAL,
# because a crawler sees only this -- never the per-player / per-team titles
# that setTitle() writes once the app boots.
PAGES = {
    "index.html": {
        "path": "/",
        "title": "NBA Career Map: where every NBA player is playing now | HoopsHype",
        "description": (
            "A live dashboard of where every NBA player is playing now \u2014 overseas "
            "signings, country hotspots, most-traveled journeymen, and club alumni."
        ),
    },
    "teams.html": {
        "path": "/teams.html",
        "title": "NBA Teams: all-time rosters for all 30 franchises | HoopsHype",
        "description": (
            "Every player who ever suited up for each NBA franchise, across all "
            "name and city eras, plus the international and minor-league clubs "
            "with the most NBA alumni."
        ),
    },
    "quiz.html": {
        "path": "/quiz.html",
        "title": "NBA Career Map Quiz: how many players can you identify by their journey?",
        "description": (
            "The route is shown, the name isn't. Guess NBA players from their "
            "career journey \u2014 how long can you last?"
        ),
    },
}

BEGIN = ("<!-- og:begin -- generated by scripts/og_tags.py. Do not hand-edit: "
         "change SITE_ORIGIN / PAGES there and re-run. -->")
END = "<!-- og:end -->"

INDENT = "    "

# Any og:/twitter: tag already in the file, generated block or not. Stripped
# before the fresh block is inserted, so re-running never leaves duplicates.
STRAY_TAG_RE = re.compile(
    r'^[ \t]*<meta\s+(?:property="og:|name="twitter:)[^>]*>[ \t]*\r?\n', re.M)
BLOCK_RE = re.compile(
    r"^[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"[ \t]*\r?\n",
    re.S | re.M)
# Insertion anchor: after the hand-written <meta name="description">, else
# after </title>.
DESC_RE = re.compile(r'^[ \t]*<meta\s+name="description"[^>]*>[ \t]*\r?\n', re.M)
TITLE_RE = re.compile(r'^[ \t]*</title>[ \t]*\r?\n', re.M)


def esc(text):
    """Escape for an HTML attribute value."""
    return (text.replace("&", "&amp;").replace('"', "&quot;")
                .replace("<", "&lt;").replace(">", "&gt;"))


def build_block(page):
    image_url = SITE_ORIGIN + OG_IMAGE_PATH
    url = SITE_ORIGIN + page["path"]
    title, desc = esc(page["title"]), esc(page["description"])
    tags = [
        ("property", "og:type", "website"),
        ("property", "og:site_name", SITE_NAME),
        ("property", "og:title", title),
        ("property", "og:description", desc),
        ("property", "og:url", url),
        ("property", "og:image", image_url),
        ("property", "og:image:width", OG_IMAGE_WIDTH),
        ("property", "og:image:height", OG_IMAGE_HEIGHT),
        ("property", "og:image:alt", esc(OG_IMAGE_ALT)),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:title", title),
        ("name", "twitter:description", desc),
        ("name", "twitter:image", image_url),
        ("name", "twitter:image:alt", esc(OG_IMAGE_ALT)),
    ]
    lines = [INDENT + BEGIN]
    lines += [f'{INDENT}<meta {kind}="{key}" content="{val}">'
              for kind, key, val in tags]
    lines.append(INDENT + END)
    return "\n".join(lines) + "\n"


def sync(filename, page):
    path = ROOT / filename
    src = path.read_text(encoding="utf-8")
    out = BLOCK_RE.sub("", src)
    out = STRAY_TAG_RE.sub("", out)

    anchor = DESC_RE.search(out) or TITLE_RE.search(out)
    if not anchor:
        raise SystemExit(
            f"{filename}: no <meta name=\"description\"> or </title> to anchor "
            f"the OG block to")
    at = anchor.end()
    out = out[:at] + build_block(page) + out[at:]
    changed = out != src
    return path, out, changed


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report drift, write nothing, exit 1 if out of sync")
    args = ap.parse_args()

    drift = []
    for filename, page in PAGES.items():
        path, out, changed = sync(filename, page)
        if not changed:
            print(f"  ok       {filename}")
            continue
        drift.append(filename)
        if args.check:
            print(f"  OUT OF SYNC {filename}")
        else:
            path.write_text(out, encoding="utf-8")
            print(f"  updated  {filename}")

    if args.check and drift:
        print(f"\n{len(drift)} file(s) out of sync. Run: python scripts/og_tags.py")
        return 1
    print(f"\nOrigin: {SITE_ORIGIN}")
    print(f"Image:  {SITE_ORIGIN}{OG_IMAGE_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
